language: node_js
node_js:
- '8'
- '7'
deploy:
  provider: heroku
  api_key:
    secure: PhEnnsX68ec95/dhK26dPzzQ5Ff7IHBQnrPVX+PyerX7Ytpw4efPAom5SZ4w3st55dPa4mbkza6KibZYyeHaHufE/DOyI9RaD4tZAZeaDyBrZyyBoZ8GCyoh5PL4wpyTcJEgETZd14CFrklJjHmRLMdwrHq/gY4ex0YiJQFYf0cPxnq9gmCGlxMxlk7q6ZrzH4lWHZvekekmZL8Qbi0A1ShAHaSsboSyjgQASN9Z2apfjxBm0GttfcyImlN0Y+lYDlrrMNjPLPCNCm4PaO512qIWIRxPZkYwabAyXqIrbSmmnU4nlQkVASApYva5UJprlY2JMoakJp7lOaNIPlrasjd6UcDchXMM9Ic7eFY+j5UOaZ3RHLeSKfsz13DscdPIRww3UasXlz/J6GpuyFDeYNhgL6ESGdKPzIbihOdd4hGTtshx17eW69XAYkxk6p1wjy1eNpEk2LIc0ocumdXhgkoINULe2cdgFEUgEmf3E+ZCyJ2MsBk6kcBY8gMTBxbRbKi7v6Wg6ncyx9CNhKw++2S44qiI5yk11d/NDmrFhwlPi9i2l8ZN503rfIecG4HGfAzD+ga9S5dReqsX2eDbZOwuIB/gfWJ/5BOS7puU5qaMBKflscpKXaU/cOhKvx1jEbO584ajv9gResa6xitIkXxd/2ZWGEF154qeIqf1ND8=
  on:
    all_branches: true
