language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: GVfPcXS/ldWOFwi1D7ZUQAfQpQGZUAh7SneV7LUq7Pn7nOCA9WKC0hzHJaITE2uIuwU/QcmIi0JtSqH+ya7siun2yTBijmc9tQ0JsygeNDoeTT7YFFHYsiVpX1wpxh0kart1fWIRUUDIJuv1Qj8ErlrHR7JwqXKTxOgDjlwPRKrZiT0df7ApZfMpiUAYcEmrX4LZHvxfFgTk9ITWZKTQNLv7nf5xN9qT1gk/kiFR7RaWiqPJ+OWvPMeMW6vYYZFU3yUVkzJZvQFCFUd+/F0Ii/xt2T1Krn0BxYBS7jG3IyBW1zVHFqYlpkX9SL4uDFxQfg6NXFOZPPeA0eavPmu/GwrTN49QIPdmlKP2N0cGHYG2CiulwsHeFMe5JweO2k032Ql5np9RicpnEWYs7TKlRJ/xnuAS9bBHh8RaIuVLTIRBdBVRKO2WZe42CJEBgUg+PeajIn7xFR/6SsUsQU06VNyucYaagVXR1ybsgyfM/nrFcKbEljLmg7S8+8AtbnZd6qna5j2/ZIN9Luknd+0K0vWdN20V3NWHr0oq/CiIKIuGXCuzww1U7y/83vghRGYvMXP+RtF896F8OB9uYX3gLr24k8u0KXQRWqxXA6O92CnLlGHI9YsDti97FIFHDYn/BlZow1GeXnVheGrrtvhtP1VSBoSq88Wr4MdbWhbvgEk=
  on:
    all_branches: true
