language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: b6DSythtttsIqi6nK2GiBg+6QJfLRSI+2nIRRNyj2HVmaauok33rRTh71/e2HCjTrx2aRPPH+UmerTiRxvGtascl9zNtRdX7tvhyIDcKTu45ebV8vjRbrWScX6OWymTA9zoNlTthpW1zPCDwqo0sL2PkxgKFANDu/Cfquuu6/5raXZRmdF2DMlHSUOBek1qZEU5D8/4XxIfgFMhRZkECoaCnMHdgdrGFaXSkXvuA5dwmzBrwTfPIgOnVVFJm7fR7lLPZN3VvvQIUGwqby2vIntDFYBcdWDi8jeumgeIJDfZWUfrrEw5h2puoywA7WHJ/BrHeCTiu7CL5HOISxf41CZnzRHoKz9Gsq43PkVKchh5HojHqExH7b664VK5+cMTw34KhRvoJ71t4WvS2UKwb63UenOEUbWACdvOtoJ7Un2JiT1U+ynlj+XHaAgBfJaBPfVzqWJ7kohYPoW9bLPMNFlqCAT7z0BQJdgygpLZTMtBX5UdP//fK5NVIZVaG0RVKikX44ROm+mcIpK65Txgb8ie5oQ2oXcKoXB7v0H3lx/6Z2IIf6MQ/CBEC+nuJcfviFmO8Fqk/ozjlINtmBHYVvtWClKMyVNERa7fEjN3xOweEfZ9SCQMa7moge8D8T4KG3kNG7H9HRlZgTDmbUxuFgVVRqi9/eFdux9uoktU5Hjo=
  on:
    all_branches: true
